# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/ubuntu-14.04"

  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "private_network", ip: "192.168.33.11"

  config.vm.hostname = "puppet-agent.local.vms.com"

  config.vm.provider :virtualbox do |vb, override|
    vb.name = "puppet_agent_centos"
  end
end
