# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"

  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.hostname = "puppet-master.local.vms.com"

  config.vm.provider :virtualbox do |vb, override|
    vb.name = "puppet_master_centos"
  end
end
